### ISSUE TITLE
Stone Tools Not Working on  EL2 - 1.08[1.16.5]

### ISSUE THREAD

**Issue by spiegelmaske** [czbuendel/EL2Test#142]
Modpack Version: 
EL2 - 1.08[1.16.5]

Stone tools no longer work. Stone pickaxe will not break cobble or basic stones.  Stone axe will not cut planks or trees, etc.
Additionally, items now stay in the regular vanilla crafting table (they didn't do this in the prior version), and the tools no longer display the number of uses remaining (they used to display this number instead of only having the red/yellow/green bar.
Not sure if those last two were purposeful changes in the update or if one thing is domino'ing into another. 

**Expected behavior**

Stone pick usually breaks basic stones.  Stone axe usually breaks wood, planks, trees, etc. 

Uninstalled and reinstalled. 
Cleared cache, cookies, etc, all the IT 101 trouble shooting.

**Comment by czbuendel** [comment]
Stone tools have never been able to used if the pack was setup correctly unless the tool was augmented with Tetra first. Natural progression disables both them and wood tools because they don't make physical sense.

Items stay in crafting tables now because of Visual Workbench (added in this version).

The durability display mod seems to have broken with the new version, we are looking for replacements.
