### ISSUE TITLE
Project MMO and FTB Quests keep crashing the game

### ISSUE THREAD

**Issue by Erithian1** [czbuendel/EL2Test#164]
Modpack Version: EL2 1.15[1.16.5]

**Describe the bug**
I try to launch Engineer's Life 2 and it crashes before even getting to the game menu. reinstalling the modpack, the 2 mods, or Java has not fixed the issue.

**To Reproduce**
1. Launch Engineers Life 2 through Multi MC
2. Loads for about 30sec 
3. Crash

**Expected behavior**
For the Modpack to load and get to the main menu

**Screenshots**
https://i.redd.it/gwbpe465pjz81.png

**Log Files**
<script src="https://gist.github.com/Erithian1/e3104a16cf0d228cbc881a1f12510cd9.js"></script>

**Comment by DoctorMage** [comment]
what launcher are you playing on

**Comment by DoctorMage** [comment]
and which version of java do you have installed

**Comment by DrLee-lihr** [comment]
confirmed
for me, neither Java 8, Java 11 or Java 14 can launch the game successfully

[https://www.curseforge.com/minecraft/modpacks/engineers-life-2?comment=218](https://www.curseforge.com/minecraft/modpacks/engineers-life-2?comment=218) it can solve the problem,
however, after using this method, the quest is not shared in multiplayer 
because it changed the ftbquests mod i can't confirm whether this quest problem is another problem of the original modpack or caused by this problem solution

**Comment by DrLee-lihr** [comment]
solved by using java 8u311 or earlier
