### ISSUE TITLE
Can't start the server using LaunchServer.bat

### ISSUE THREAD

**Issue by Guilhem-Virtualis** [czbuendel/EL2Test#179]
Modpack Version: EL2-1.16.5-1.17

**Describe the bug**
Server dowloaded from curseforge
Started using LaunchServer.bat
Error displayed in the console :

**Log Files**
https://gist.github.com/Guilhem-Virtualis/c731a671d70bb66b36a83fc6bdbad989

**Comment by DoctorMage** [comment]
Looks like you have Java 9 - 19 installed.
You need to specify Java 8 path in .bat file.

1  Download Java 8 here https://www.java.com/en/download/manual.jsp (Offline or Online install 64 bit)
2  Go to C:\Program Files\Java and see what Java version you have. You need the one starting with 1.8.0...

![image](https://user-images.githubusercontent.com/85318453/208774428-9fbccf00-445f-4700-a8a7-75f2a13cb7fc.png)


3   Right here I have jre1.8.0_291 That's the one we need! Probably for you it will be different.
4  Now you need to specify the exact path in .bat:
5  Open LaunchServer.bat with notepad
6  Instead of Java specify your full path to Java
7  For me the whole file would look like this:   "C:\Program Files\Java\jre1.8.0_291\bin\java.exe" -Xmx4G -jar forge-1.16.5-36.2.33.jar nogui pause

![image](https://user-images.githubusercontent.com/85318453/208774615-64e6ec90-d104-434d-a813-e7572d2bc8b5.png)

**Comment by Guilhem-Virtualis** [comment]
Thank you, it works perfectly with the version 1.8.0_261 of java!

Here's my LaunchServer.bat (I had to remove the first "java" and replace "4G" by "4g"):
"C:\Program Files\Java\jdk1.8.0_261\bin\java.exe" -Xmx4g -jar forge-1.16.5-36.2.33.jar nogui
pause
