### ISSUE TITLE
two books you need for two different quest line

### ISSUE THREAD

**Issue by donman990** [czbuendel/EL2Test#31]
I found two book we can not craft 
One is in the transportation quest line we can not craft the book advanced transport
Second one is in becoming an engineer we can not craft the book engineer's decor

**Comment by D0CTOR-ZED** [comment]
You can look up the recipes for the books in JEI.  Engineer's Decor is crafted using a book with two iron nuggets, one below the book and one to the right of it in a crafting grid.  Advanced Transport are crafted using a Book and a Rail in a crafting grid.  The quest entries may show that the books are not a valid item, but the text of the quest explains this and says to search for the recipes in JEI.  Since they can be crafted and are recognized by the quests, I'm assuming using the quest book to find the recipe was the issue and I'm closing this issue.  If you are still having trouble, please make sure you are on the most recent version and re-open the issue.
