### ISSUE TITLE
Small laboratory furnace voids upon breaking

### ISSUE THREAD

**Issue by MicanJoe** [czbuendel/EL2Test#32]
Modpack Version: 1.01a

**Describe the bug**
The small laboratory furnace from immersive decor void its inventory when broken. This applies to the Fuel and the items to be/already smelted but not to the two external heater slots. Its probably the same bug that happened with the Labeled crates in the last version

**To Reproduce**
See above

**Expected behavior**
For the furnace to either keep its whole inventory or drop the items on the ground

**Screenshots**
NIL
**Log Files**
NIL

**Comment by czbuendel** [comment]
![image](https://user-images.githubusercontent.com/23238026/115985470-9edb6d00-a571-11eb-98f4-96bcfb61a40b.png)
And then I break it and re-place it down.
![image](https://user-images.githubusercontent.com/23238026/115985489-b31f6a00-a571-11eb-8969-42f48584eb7a.png)
This should be fixed in the next update then. ED had some updates that I think fixed the issue.

**Comment by MicanJoe** [comment]
Yeah just checked and it works regurlarly, dumb me. It got probably mixed with another furnace that i had in the inventory (altho i was sure to have only one at the time).
