### ISSUE TITLE
Conveyor belt make you go on a crash look

### ISSUE THREAD

**Issue by ItzSwapnil** [czbuendel/EL2Test#67]
So whenever you stand on a conveyor belt your it will crash you immediately and you can't join the server again until the belt is broken by someone else

**Comment by czbuendel** [comment]
Well if you would have followed the template like you were supposed to you should have provided the latest.log log that we need to fix errors. 
As far as repeatability I just rode circles on conveyors for about 5 minutes with no issues.

So provide a log file, otherwise this will eventually be closed.
