### ISSUE TITLE
Neptunium Bow still requires an arrow in the inventory for Infinity

### ISSUE THREAD

**Issue by 5il3nc3r** [czbuendel/EL2Test#69]
Modpack Version: 1.02a

**Describe the bug**
Vanilla Bows with Infinity no longer require an arrow in the inventory to shoot. However, the Neptunium Bow does.
Assuming whatever mod/change was done to "fix" the vanilla bows didn't carry over to the Neptunium one.

**To Reproduce**
1. Get a Neptunium Bow
2. Put the Infinity Enchant on it
3. Attempt to fire it without any arrows in the inventory
4. Notice how it won't shoot, despite having the Infinity enchant

**Expected behavior**
Since it has been made so vanilla bows with Infinity can shoot arrows without having to carry one on you, this change should be applied to all available bows, unless clearly explained why not.

**Comment by D0CTOR-ZED** [comment]
This isn't a modpack issue.  If infinity is being changed by a mod, it would be up to that mod to decide if it wants to include the neptunium bow in its changes.  As far as such things go, it is beyond the scope of a modpack to clearly explain every nuance of every change made by every mod in the pack.

There is something to be said for exploration and discovery.  If someone learns that they can fire their infinity bow without arrows through game play, that is part of the game.  If they then learn that they can't do the same with their neptunium bow, that is also part of the game.

I'm leaving this open for now.  When I can I'll check which mod makes this change and if there is anything that can be done about it.

**Comment by D0CTOR-ZED** [comment]
The ability for non-modded bows to fire without requiring arrows in the inventory appears to be added by CoFH Core, based on a test where removing it disabled the ability and restoring it returned the ability.  CoFH Core appears to add their own bow class, so neither the vanilla crossbow nor modded bows will gain this ability, unless that modded bow is made specifically using CoFH Core.  Only the vanilla minecraft bow gaining the perk appears to be by design.
